Rubin-env 0.1.1 (with eups) and removed unnecessary code

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -270,45 +270,24 @@ main() {
     mv "${LSSTSW}/eups-tmp" "${LSSTSW}/eups/legacy"
     ln -s legacy "${LSSTSW}/eups/current"
   )
-
-  # if a LSST_EUPS_GITREV is set, use that as the version dir name
-  if [[ -n $LSST_EUPS_GITREV ]]; then
-    LSST_EUPS_VERSION=$LSST_EUPS_GITREV
-  fi
-
-  test -f "${LSSTSW}/eups/${LSST_EUPS_VERSION}/.deployed" || ( # EUPS
-    echo "::: Deploying eups ${LSST_EUPS_VERSION}"
-    if [[ -e "${LSSTSW}/eups/${LSST_EUPS_VERSION}" ]]; then
-      chmod -R +w "${LSSTSW}/eups/${LSST_EUPS_VERSION}"
-      rm -rf "${LSSTSW}/eups/${LSST_EUPS_VERSION}"
-    fi
-
-    cd sources
-    if [[ -n $LSST_EUPS_GITREV ]]; then
-      git clone "$LSST_EUPS_GITREPO" eups
-      cd eups
-      git checkout "$LSST_EUPS_GITREV"
-    else
-      $CURL "${CURL_OPTS[@]}" -L \
-        -o "eups-${LSST_EUPS_VERSION}.tar.gz" \
-        "https://github.com/RobertLuptonTheGood/eups/archive/${LSST_EUPS_VERSION}.tar.gz"
-      tar xzf "eups-${LSST_EUPS_VERSION}.tar.gz"
-      cd "eups-${LSST_EUPS_VERSION}"
-    fi
-
-    ./configure \
-      --prefix="${LSSTSW}/eups/${LSST_EUPS_VERSION}" \
-      --with-python="${LSSTSW}/miniconda/bin/python" \
-      --with-eups="${EUPS_PATH}"
-    make
-    make install
-    touch "${LSSTSW}/eups/${LSST_EUPS_VERSION}/.deployed"
+  # backwards compatibility if EUPS was installed to a versioned directory (not from conda)
+   test ! -f "${LSSTSW}/eups/${LSST_EUPS_VERSION}/.deployed" || ( # EUPS
+    echo "::: Moving old EUPS to eups-legacy"
+    mv "${LSSTSW}/eups" "${LSSTSW}/eups-legacy"
   )
 
-  if [[ "$(readlink "${LSSTSW}/eups/current")" != "$LSST_EUPS_VERSION" ]]; then
-    echo "::: Making eups ${LSST_EUPS_VERSION} the default"
-    rm -f "${LSSTSW}/eups/current"
-    ln -s "${LSST_EUPS_VERSION}" "${LSSTSW}/eups/current"
+  # check if eups is not already available in the environment
+  # made it available in a separe eups-base environment
+  if ! command -v eups > /dev/null; then
+    echo "error: No eups found in the active environment ..."
+    echo "  ... trying to use a stacked eups-base environment"
+    conda deactivate
+    if ! conda env list | grep "^eups-base " > /dev/null; then
+      echo "::: Creating eups-base environment"
+      conda create -y --name eups-base eups -c conda-forge
+    fi
+    conda activate eups-base
+    conda activate --stack "$LSST_CONDA_ENV_NAME"
   fi
 
   mkdir -p "${EUPS_PATH}"/{site,ups_db}
diff --git a/bin/envconfig b/bin/envconfig
--- a/bin/envconfig
+++ b/bin/envconfig
@@ -89,20 +89,10 @@ source "${LSSTSW}/etc/settings.cfg.sh"
 # shellcheck disable=SC2154
 . "${miniconda_path}/etc/profile.d/conda.sh"
 
-if [[ ! -f "$LSSTSW/eups/current/bin/setups.$SUFFIX" ]]; then
-  echo "error: eups not found in $LSSTSW/eups/current" 1>&2
-  echo "  you may need to [re]run bin/deploy to [re]deploy EUPS." 1>&2
-  return
-fi
-
 export PATH="$LSSTSW/lfs/bin:$PATH"
 export PATH="$LSSTSW/bin:$PATH"
 
 export MANPATH="$LSSTSW/lfs/share/man:"
-
-# need to activate the miniconda base environment to get the correct list of environments
-# shellcheck disable=SC1091
-conda activate base
 
 if $INTERACTIVE ; then
   raw_envs=()
@@ -161,8 +151,19 @@ else
 fi
 export LSST_CONDA_ENV_NAME
 
-# shellcheck disable=SC1090
-. "$LSSTSW/eups/current/bin/setups.$SUFFIX"
+# check if eups is not already available in the environment
+# made it available in a separe eups-base environment
+if ! command -v eups > /dev/null; then
+  echo "error: No eups found in the active environment ..."
+  echo "  ... trying to use a stacked eups-base environment"
+  conda deactivate
+  if ! conda env list | grep "^eups-base " > /dev/null; then
+    echo "::: Creating eups-base environment"
+    conda create -y --name eups-base eups -c conda-forge
+  fi
+  conda activate eups-base
+  conda activate --stack "$LSST_CONDA_ENV_NAME"
+fi
 
 # definition EUPS_PATH depending on the environment:
 # removing from the ENV_name the default prefix defined in SPLENV_BASE_NAME
