allow overriding miniconda installer + conda channel(s)

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -12,6 +12,8 @@ EUPS_GITREV=${EUPS_GITREV:-""}
 EUPS_GITREPO=${EUPS_GITREPO:-"https://github.com/RobertLuptonTheGood/eups.git"}
 MINICONDA2_VERSION=${MINICONDA2_VERSION:-4.2.12} # Version of Miniconda to install
 MINICONDA3_VERSION=${MINICONDA3_VERSION:-4.2.12} # Version of Miniconda to install
+MINICONDA_BASE_URL=${MINICONDA_BASE_URL:-https://repo.continuum.io/miniconda}
+CONDA_CHANNELS=${CONDA_CHANNELS:-""}
 GIT_VERSION=${GIT_VERSION:-2.2.2}           # Version of git to install
 LFS_VERSION=${LFS_VERSION:-1.5.5}           # Version of git-lfs to install
 
@@ -89,10 +91,33 @@ test -f "${LSSTSW}/miniconda/.deployed" || ( # Anaconda
 
     miniconda_file_name="Miniconda${PYVER_PREFIX}-${MINICONDA_VERSION}-${ANA_PLATFORM}.sh"
     echo "::: Deploying Miniconda${PYVER_PREFIX} ${MINICONDA_VERSION} for ${ANA_PLATFORM}"
-    curl -# -L -O "http://repo.continuum.io/miniconda/${miniconda_file_name}"
+    curl -# -L -O "${MINICONDA_BASE_URL}/${miniconda_file_name}"
     bash "$miniconda_file_name" -b -p "${LSSTSW}/miniconda"
 
     touch "${LSSTSW}/miniconda/.deployed"
+)
+
+(
+    # configure alt conda channel(s)
+    if [[ -n $CONDA_CHANNELS ]]; then
+        # shellcheck disable=SC2030
+        export PATH="$LSSTSW/miniconda/bin:$PATH"
+
+        # remove any previously configured non-default channels
+        # XXX allowed to fail
+        set +e
+        conda config --remove-key channels
+        set -e
+
+        for c in $CONDA_CHANNELS; do
+            conda config --add channels "$c"
+        done
+
+        # remove the default channels
+        conda config --remove channels defaults
+
+        conda config --show
+    fi
 )
 
 test -f "${LSSTSW}/miniconda/.packages.deployed" || ( # conda packages
@@ -101,6 +126,7 @@ test -f "${LSSTSW}/miniconda/.packages.deployed" || ( # conda packages
     # XXX note that
     # https://github.com/lsst/miniconda2/blob/master/ups/eupspkg.cfg.sh
     # uses the conda package specification from this repo.
+    # shellcheck disable=SC2031
     export PATH="$LSSTSW/miniconda/bin:$PATH"
 
     ARGS=()
