Allow for building rsp with flag -R

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -23,6 +23,7 @@ LSST_BUILD_GITREV=${LSST_BUILD_GITREV:-main}
 LSST_BUILD_GITREPO=${LSST_BUILD_GITREPO:-https://github.com/lsst/lsst_build.git}
 LSST_SCIPIPECENV_GITREPO=${LSST_SCIPIPECENV_GITREPO:-https://github.com/lsst/scipipe_conda_env.git}
 LSST_RUBIN_ENV_NAME="rubin-env"
+LSST_ADD_RSP=${LSST_ADD_RSP:-false}
 set -e
 
 
@@ -40,6 +41,7 @@ usage() {
 	    -v VERSION  a specific version of rubin-env conda package.
 	                By default will use the version specified in etc/settings.cfg.sh
 	    -r REF      git reference (SHA1) in scipipe_conda_env repository (backward compatibility)
+      -R RSP      downloads rubin-env-rsp version of conda package
 	    -x TAG      eups tag to select the exact environment for that tag
     -V VARIANT  install a specific rubin-env variant, like rubin-env-developer
 	    -h          show this message
@@ -55,7 +57,7 @@ parse_args() {
 
   # We are intentionally not using gnu `getopt` due to portability concerns.
   # Sadly, this means no long options without a massive amount of boilerplate.
-  while getopts "hr:v:x:V:" opt; do
+  while getopts "hr:v:x:V:R" opt; do
     case "$opt" in
     h)
       usage
@@ -75,6 +77,11 @@ parse_args() {
       [[ -n $TAG ]] && usage "Cannot specify both -r and -x"
       [[ -n $ENV_VERSION ]] && usage "Cannot specify both -r and -v"
       ENVREF=${OPTARG}
+      ;;
+    R)
+      [[ -n $TAG ]] && usage "Cannot specify both -R and -x"
+      [[ -n $ENVREF ]] && usage "Cannot specify both -R and -r"
+      LSST_ADD_RSP=true
       ;;
     V)
       [[ -n $TAG ]] && usage "Cannot specify both -V and -x"
@@ -128,8 +135,13 @@ get_tagged_env() {
   else
     fail "Unknown platform or arch: $platform $arch"
   fi
-  $CURL "${CURL_OPTS[@]}" -O "$eups_root/$eups_platform/env/$1.env" \
-    || fail "Unable to download environment spec for tag $1"
+  fetch_url="$eups_root/$eups_platform/env/$1.env"
+  if [[ $ENABLE_RSP ]]; then
+    fetch_url="$eups_root/$eups_platform/env/$1-rsp.env"
+  fi
+
+  $CURL "${CURL_OPTS[@]}" -O "$fetch_url" \
+    || fail "Unable to download environment spec for tag $1 at $fetch_url"
 }
 
 main() {
@@ -137,6 +149,7 @@ main() {
 
   ENV_VERSION=""
   ENVREF=""
+
 
   parse_args "$@"
 
@@ -155,13 +168,18 @@ main() {
   if [[ -n $ENV_NAME ]]; then
     LSST_RUBIN_ENV_NAME="$ENV_NAME"
   fi
+  echo "Bye"
+  if [[ $LSST_ADD_RSP ]]; then
+    LSST_RUBIN_ENV_NAME="$LSST_RUBIN_ENV_NAME-rsp"
+  fi
 
   if [[ "$RUBIN_ENV_VERSION" == *dev* ]]; then
     RUBIN_ENV_CONDA_CHANNELS="nodefaults conda-forge/label/rubin-env_dev conda-forge"
   fi
   LSST_CONDA_CHANNELS=${LSST_CONDA_CHANNELS:-"${RUBIN_ENV_CONDA_CHANNELS}"}
 
-  export LSST_CONDA_ENV_NAME=${LSST_CONDA_ENV_NAME:-"${SPLENV_BASE_NAME}-${RUBIN_ENV_VERSION}"}
+  suffix=$([ "$LSST_ADD_RSP" = true ] && echo "-rsp" || echo "")
+  export LSST_CONDA_ENV_NAME=${LSST_CONDA_ENV_NAME:-"${SPLENV_BASE_NAME}-${RUBIN_ENV_VERSION}${suffix}"}
 
   mkdir -p "${LSSTSW}"/{sources,build,var/run,var/log,lfs,distserver/production,etc,env}
 
