Use tag for env name.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -97,24 +97,24 @@ am_I_sourced() {
 
 get_tagged_env() {
   eups_root=https://eups.lsst.codes/stack
-  RUBIN_ENV_VERSION=$($CURL "${CURL_OPTS[@]}" -L "$eups_root/src/tags/${TAG}.list" \
+  env_version=$($CURL "${CURL_OPTS[@]}" -L "$eups_root/src/tags/$1.list" \
     | grep '^#CONDA_ENV=' | cut -d= -f2) \
     || fail "Unable to determine conda env"
   platform="$(uname -s)"
   case "$platform" in
     Linux)
-      eups_platform="redhat/el7/conda-system/miniconda3-${LSST_MINICONDA_VERSION}-$RUBIN_ENV_VERSION"
+      eups_platform="redhat/el7/conda-system/miniconda3-${LSST_MINICONDA_VERSION}-$env_version"
       ;;
     Darwin)
-      eups_platform="osx/10.9/conda-system/miniconda3-${LSST_MINICONDA_VERSION}-$RUBIN_ENV_VERSION"
+      eups_platform="osx/10.9/conda-system/miniconda3-${LSST_MINICONDA_VERSION}-$env_version"
       ;;
     *)
       fail "Unknown platform: $platform"
       ;;
   esac
 
-  $CURL "${CURL_OPTS[@]}" -O "$eups_root/$eups_platform/env/${TAG}.env" \
-    || fail "Unable to download environment spec for tag ${TAG}"
+  $CURL "${CURL_OPTS[@]}" -O "$eups_root/$eups_platform/env/$1.env" \
+    || fail "Unable to download environment spec for tag $1"
 }
 
 main() {
@@ -131,7 +131,7 @@ main() {
     RUBIN_ENV_VERSION=$ENVREF
   elif [[ -n $TAG ]]; then
     RUBIN_ENV_VERSION=$TAG
-    get_tagged_env
+    get_tagged_env "$TAG"
   else
     RUBIN_ENV_VERSION=$LSST_SPLENV_REF
   fi
@@ -201,7 +201,7 @@ main() {
         ARGS+=("-c $c")
       done
       if [[ -n $TAG ]]; then
-	ARGS+=("--file" ${TAG}.env)
+	ARGS+=("--file" "${TAG}.env")
       else
         ARGS+=("rubin-env=${RUBIN_ENV_VERSION}")
       fi
@@ -334,11 +334,9 @@ main() {
   echo "::: To activate the just deployed environment use the following command:"
   echo
 
-  if [[ $ENV_VERSION == '' ]]; then
+  if [[ -z "$ENV_VERSION" ]] && [[ -z "$ENVREF" ]] && [[ -z "$TAG" ]]; then
     if [[ $SHELL =~ bash$ ]]; then
       echo "    . ${LSSTSW}/bin/envconfig"
-    elif [[ $SHELL =~ csh$ ]]; then # Supports tcsh
-      echo "    source ${LSSTSW}/bin/envconfig.csh"
     elif [[ $SHELL =~ zsh$ ]]; then
       echo "    . ${LSSTSW}/bin/envconfig"
     else
