Change if-elsif-else block to a case statement
Makes the code more readable.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -20,15 +20,14 @@ export PATH="$LSSTSW/bin:$PATH"
 
 test -f "$LSSTSW/anaconda/.deployed" || ( # Anaconda
 	cd sources
-    platformName=$(uname -s)
-    if [ ${platformName:0:5} == "Linux" ]; then
-        anaPlatform="Linux-x86_64"
-    elif [ ${platformName:0:6} == "Darwin" ]; then
-        anaPlatform="MacOSX-x86_64"
-    else
-        echo "Cannot install anaconda: unsupported platform $platformName"
-        exit 1
-    fi
+    case $(uname -s) in
+        Linux*)  anaPlatform="Linux-x86_64" ;;
+        Darwin*) anaPlatform="MacOSX-x86_64" ;;
+        *)
+          echo "Cannot install anaconda: unsupported platform $(uname -s)"
+          exit 1
+          ;;
+    esac
     anaFileName="Anaconda-${ANACONDA_VERSION}-${anaPlatform}.sh"
     echo "::: Deploying Anaconda ${ANACONDA_VERSION} for ${anaPlatform}"
 	curl -# -L -O http://repo.continuum.io/archive/${anaFileName}
