update exit status to indicate if prepare completed
Add 128 to non-zero exit statuses if the `lsst-build prepare` subcommand has
completed.  This is to allow consumer scripts to be able to determine if a
failure in this script occurred before or after the prepare step.

diff --git a/bin/rebuild b/bin/rebuild
--- a/bin/rebuild
+++ b/bin/rebuild
@@ -16,6 +16,25 @@
 #     (mkdir versiondb; cd versiondb; git init; mkdir dep_db ver_db manifests)
 #
 
+# true if `lsst-build prepare` has run successfully
+PREPARED=false
+
+#
+# Add 128 to non-zero exit statuses if the `lsst-build prepare` subcommand has
+# completed.  This is to allow consumer scripts to be able to determine if a
+# failure in this script occurred before or after the prepare step.
+#
+cleanup() {
+    local rv=$?
+
+    [[ $rv == 0 ]] && exit
+    [[ $PREPARED == true ]] && [[ $rv -lt 128 ]] && rv=$((rv + 128))
+
+    exit $rv
+}
+
+trap cleanup EXIT
+
 set -e
 DIR=$(cd "$(dirname "$0")"; pwd)
 . "${DIR}/../etc/settings.cfg.sh"
@@ -69,11 +88,23 @@ fi
     #
     VERSIONDBHEAD=$(cd "$VERSIONDB" && git rev-parse HEAD)
     [[ -z $NOPUSH ]] && (cd "$VERSIONDB" && git pull --quiet)
+
+    ARGS=()
     if [[ $NO_FETCH == 1 ]]; then
-        lsst-build prepare --no-fetch --repos="${REPOSFILE}" --exclusion-map="$EXCLUSIONS" --version-git-repo="$VERSIONDB" "$LSSTSW_BUILD_DIR" "${PRODUCTS[@]}" "$REF"
-    else
-        lsst-build prepare --repos="${REPOSFILE}" --exclusion-map="$EXCLUSIONS" --version-git-repo="$VERSIONDB" "$LSSTSW_BUILD_DIR" "${PRODUCTS[@]}" "$REF"
+        ARGS+=("--no-fetch")
     fi
+    ARGS+=("--repos=${REPOSFILE}")
+    ARGS+=("--exclusion-map=${EXCLUSIONS}")
+    ARGS+=("--version-git-repo=${VERSIONDB}")
+    ARGS+=("$LSSTSW_BUILD_DIR")
+    if [[ ! -z "$REF" ]]; then
+        # XXX intentionally not quoted to allow word splitting
+        ARGS+=($REF)
+    fi
+    ARGS+=(${PRODUCTS[@]})
+
+    lsst-build prepare "${ARGS[@]}"
+
     [[ -z $NOPUSH && "$VERSIONDBHEAD" != $(cd "$VERSIONDB" && git rev-parse HEAD) ]] && (cd "$VERSIONDB" && git push && git push --tags)
 
     eval "$(grep -E '^BUILD=' "$LSSTSW_BUILD_DIR"/manifest.txt)"
@@ -82,6 +113,8 @@ fi
     if [[ "$PREP_ONLY" == 1 ]]; then
         exit
     fi
+
+    PREPARED=true
 
     #
     # HACK: Speed up the build by assuming EUPS caches are up-to-date
