Final improvement from KT reivew

diff --git a/bin/rebuild b/bin/rebuild
--- a/bin/rebuild
+++ b/bin/rebuild
@@ -67,14 +67,12 @@ save_build_env() {
     local_env_file="${local_env_dir}/${ref_file}"
     echo -e "\nenv_ref_file: ${local_env_file}\n" >> "${filename}"
     grep -v "^name" "${local_env_file}" > "${ref_env}"
-    # save diff in file
-    echo "Differences between active anvironment and reference environment:" >> "${filename}"
-    echo "Differences between active anvironment and reference environment:"
-    diff -B "${active_env}" "${ref_env}" >> "${filename}" || true  # OK for this to fail
-    # show diff in output
-    diff -u "${active_env}" "${ref_env}" || true  # OK for this to fail
-    echo "^^^^ end of diff ^^^^^^^" >> "${filename}"
-    echo "^^^^ end of diff ^^^^^^^"
+    # save diff in file and print it to console
+    {
+      echo "Differences between active anvironment and reference environment:"
+      diff -B -C0 "${active_env}" "${ref_env}" || true  # OK for this to fail
+      echo "^^^^ end of diff ^^^^^^^"
+    } | tee -a "${filename}"
   else
     echo "No environment file definition in ${local_env_dir}. Nothing recorded."
   fi
